server:
  address: localhost
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techsupp
    username: root
    password: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
image:
  path: C:/Temp
#  servlet:          # Spring multipart 인터페이스를 활용하여 파일 업로드 기능 구현
#    multipart:
#      file-size-threshold: 1MB
#      location: C:/Temp
#      max-file-size: 100MB
#      max-request-size: 100MB
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace